services:
  workout-builder:
    build: .
    container_name: workout-builder
    ports:
      - "5010:8080"
    restart: unless-stopped
    networks:
      - workout

networks:
  workout:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.144/28
